modLoader="javafml"
loaderVersion="[34,)"
license="MIT License"
issueTrackerURL="http://www.github.com/MelanX/cucurbita/issues/"

[[mods]]
modId="cucurbita"
version="${file.jarVersion}"
displayName="Cucurbita"
updateJSONURL="https://raw.githubusercontent.com/MelanX/mod-updatechecker-files/master/cucurbita.json"
displayURL="www.curseforge.com/members/melanx/"
#logoFile="cucurbita.png"
credits=""
authors="MelanX"
description='''

'''

[[dependencies.cucurbita]]
    modId="forge"
    mandatory=true
    versionRange="[34.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cucurbita]]
    modId="libx"
    mandatory=true
    versionRange="[0.1.9,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cucurbita]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3, 1.17)"
    ordering="NONE"
    side="BOTH"
